import '../app/data/models/product_model.dart';
import 'constants.dart';

class DummyHelper {
  const DummyHelper._();

  static List<ProductModel> products = [
    ProductModel(
        id: 1,
        image: Constants.pc1,
        name: 'Asus Rog Zephyrus M16',
        quantity: 0,
        price: 157120,
        rating: 4.8,
        reviews: '1.7 bin satın alma',
        size: 'Siyah',
        isFavorite: false,
        information:
            'İşlemci Markası:Intel\nİşlemci Nesli:13. Nesil\nİşlemci Teknolojisi:Core i9\nİşlemci Numarası:13900H\nİşlemci Hızı:Turbo Boost 5.4 GHz\nRam (Sistem Belleği):32 GB (2x16GB)\nRam Tipi:DDR5\nRam Hafıza Bus Hızı:4800 MHz'),
    ProductModel(
        id: 2,
        image: Constants.pc2,
        name: 'Asus Rog Strix Scar 18',
        quantity: 0,
        price: 150359,
        rating: 4.7,
        reviews: '1.5 bin satın alma',
        size: 'Siyah',
        isFavorite: false,
        information:
            'İşlemci Markası:Intel\nİşlemci Nesli:13. Nesil\nİşlemci Teknolojisi:Core i9\nİşlemci Numarası:13980HX\nİşlemci Hızı:Turbo Boost 5.6 GHz\nRam (Sistem Belleği):32 GB (2x16GB)Ram Tipi:DDR5\nRam Hafıza Bus Hızı:4800 MHz'),
    ProductModel(
        id: 3,
        image: Constants.pc3,
        name: 'MacBook Pro MUW63TU/A',
        quantity: 0,
        price: 148999,
        rating: 4.8,
        reviews: '2 bin satın alma',
        size: 'Siyah',
        isFavorite: false,
        information:
            'İşlemci Markası:Apple\nİşlemci Teknolojisi:M3 Max\nİşlemci Numarası:Paylaşılmıyor\nİşlemci Hızı:Paylaşılmıyor\nRam (Sistem Belleği):48 GB\nRam Tipi:Birleşik Bellek\nDisk Kapasitesi:1 TB\nDisk Türü:SSD'),
    ProductModel(
      id: 4,
      image: Constants.pc4,
      name: 'MacBook Pro MRW33TU/A',
      quantity: 0,
      price: 130999,
      rating: 4.7,
      reviews: '2.5 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'İşlemci Markası:Apple\nİşlemci Teknolojisi:M3 Max\nİşlemci Numarası:Paylaşılmıyor\nİşlemci Hızı:Paylaşılmıyor\nRam (Sistem Belleği):36 GB\nRam Tipi:Birleşik Bellek\nDisk Kapasitesi:1 TB\nDisk Türü:SSD',
    ),
    ProductModel(
      id: 5,
      image: Constants.pc5,
      name: 'Lenovo Legion Pro 7',
      quantity: 0,
      price: 147999,
      rating: 4.7,
      reviews: '5 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'İşlemci Markası:Intel\nİşlemci Nesli:13. Nesil\nİşlemci Teknolojisi:Core i9\nİşlemci Numarası:13900HX\nİşlemci Hızı:Turbo Boost 5.4 GHz\nRam (Sistem Belleği):32 GB (2x16GB)Ram Tipi:DDR5\nRam Hafıza Bus Hızı:5600 MHz',
    ),
    ProductModel(
      id: 6,
      image: Constants.pc6,
      name: 'Lenovo Legion 7 Pro',
      quantity: 0,
      price: 127999,
      rating: 4.8,
      reviews: '4.6 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'İşlemci Markası:Intel\nİşlemci Nesli:13. Nesil\nİşlemci Teknolojisi:Core i9\nİşlemci Numarası:13900HX\nİşlemci Hızı:Turbo Boost 5.4 GHz\nRam (Sistem Belleği):32 GB (2x16GB)Ram Tipi:DDR5\nRam Hafıza Bus Hızı:5600 MHz',
    ),
    ProductModel(
      id: 7,
      image: Constants.pc7,
      name: 'Msi Creator Z17',
      quantity: 0,
      price: 114445,
      rating: 4.6,
      reviews: '2 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'İşlemci Markası:Intel\nİşlemci Nesli:13. Nesil\nİşlemci Teknolojisi:Core i7\nİşlemci Numarası:13700HX\nİşlemci Hızı:Turbo Boost 5.0 GHz\nRam (Sistem Belleği):32 GB (2x16GB)Ram Tipi:DDR5\nRam Hafıza Bus Hızı:4800 MHz',
    ),
    ProductModel(
      id: 8,
      image: Constants.pc8,
      name: 'Msi Gp68 Vector',
      quantity: 0,
      price: 148999,
      rating: 4.8,
      reviews: '2 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'İşlemci Markası:Intel\nİşlemci Nesli:Intel 13.Nesil\nİşlemci Nesli:13. Nesil\nİşlemci Teknolojisi:Core i9\nİşlemci Numarası:13980HX\nİşlemci Hızı:4.0 GHz Turbo Boost 5.6 GHz\nRam (Sistem Belleği):32 GB\nRam Tipi:DDR5',
    ),
    ProductModel(
      id: 9,
      image: Constants.pc9,
      name: 'Acer Predator',
      quantity: 0,
      price: 97999,
      rating: 4.5,
      reviews: '2 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'İşlemci Markası:Intel\nİşlemci Nesli:13. Nesil\nİşlemci Teknolojisi:Core i9\nİşlemci Numarası:13900HX\nİşlemci Hızı:Turbo Boost 5.4 GHz\nRam (Sistem Belleği):32 GBRam Tipi:DDR5\n"Disk Kapasitesi:1 TB',
    ),
    ProductModel(
      id: 10,
      image: Constants.pc10,
      name: 'Hp Omen 17-ck2006nt',
      quantity: 0,
      price: 148999,
      rating: 4.4,
      reviews: '2 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'İşlemci Markası:Intel\nİşlemci Nesli:13. Nesil\nİşlemci Teknolojisi:Core i9\nİşlemci Numarası:13900HX\nİşlemci Hızı:Turbo Boost 5.4 GHz\nRam (Sistem Belleği):32 GB (2x16GB)Ram Tipi:DDR5\nRam Hafıza Bus Hızı:5200 MHz',
    ),
    ProductModel(
      id: 11,
      image: Constants.tlp1,
      name: 'iPhone 15 Pro Max',
      quantity: 0,
      price: 99999,
      rating: 4.7,
      reviews: '1.5 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Boyutu:6,7\nDahili Hafıza:1 TB\nMobil Ram Boyutu (GB):8 GBPil Gücü:4442 mAh\nEkran Yenileme Hızı:120 Hz\nKamera Çözünürlük:48 mp +12 mp + 12 mp\nSuya Dayanıklılık:IP68\nSuya Dayanıklılık:IP68',
    ),
    ProductModel(
      id: 12,
      image: Constants.tlp2,
      name: 'iPhone 14 Pro Max',
      quantity: 0,
      price: 87457,
      rating: 4.6,
      reviews: '2.5 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Boyutu:6.7 inch\nDahili Hafıza:1TB\nMobil Ram Boyutu (GB):6 GB\nPil Gücü:4323 mAh\nEkran Yenileme Hızı:120 Hz\nKamera Çözünürlük:48 mp +12 mp + 12 mp\nSuya Dayanıklılık:Var\nİşlemci Hızı:Belirtilmemiş',
    ),
    ProductModel(
      id: 13,
      image: Constants.tlp3,
      name: 'Samsung Galaxy Z',
      quantity: 0,
      price: 63999,
      rating: 4.5,
      reviews: '3.4 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Boyutu:7,6 inch\nDahili Hafıza:512 GB\nMobil Ram Boyutu (GB):12 GB\nPil Gücü:4440 mAh\nEkran Yenileme Hızı:120 Hz\nKamera Çözünürlük:50 mp + 12 mp + 10 mp\nSuya Dayanıklılık:Var\nİşlemci Hızı:3.36GHz,2.8GHz,2GHz',
    ),
    ProductModel(
      id: 14,
      image: Constants.tlp4,
      name: 'Samsung Galaxy S23',
      quantity: 0,
      price: 56999,
      rating: 4.7,
      reviews: '3.7 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Boyutu:6.8 inch\nMobil Ram Boyutu (GB):12 GB\nPil Gücü:5000 mAh\nEkran Yenileme Hızı:120 Hz\nKamera Çözünürlük:15 - 20 MP\nSuya Dayanıklılık:Var\nİşlemci Hızı:3.36GHz,2.8GHz,2GHz\nCep Telefonu Modeli:S23 ULTRA',
    ),
    ProductModel(
      id: 15,
      image: Constants.tlp5,
      name: 'HUAWEI P60 PRO',
      quantity: 0,
      price: 39999,
      rating: 4.6,
      reviews: '1.7 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Boyutu:6,67 inch\nDahili Hafıza:256 GB\nMobil Ram Boyutu (GB):8 GB\nPil Gücü:4815 mAH\nEkran Yenileme Hızı:120 Hz\nKamera Çözünürlük:48 MP+13 MP+48 MP\nSuya Dayanıklılık:Var\nİşlemci Hızı:    Octa-core, 1 x Cortex-X2@3.2 GHz + 3',
    ),
    ProductModel(
      id: 16,
      image: Constants.tlp6,
      name: 'HUAWEI NOVA 11',
      quantity: 0,
      price: 22299,
      rating: 4.5,
      reviews: '0.9 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Boyutu:6,78 inch\nDahili Hafıza:256 GB\nMobil Ram Boyutu (GB):8 GB\nPil Gücü:4500 mAh\nEkran Yenileme Hızı:120 Hz\nKamera Çözünürlük:50 MP\nSuya Dayanıklılık:Yok\nİşlemci Hızı:1 x 2.4GHz & 3 x',
    ),
    ProductModel(
      id: 17,
      image: Constants.tab1,
      name: 'iPad Pro 6',
      quantity: 0,
      price: 70999,
      rating: 4.7,
      reviews: '2.1 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Disk Kapasitesi:1 TB\nEkran Boyutu:12.9 inch\nÇözünürlük (Piksel):2732 x 2048\nRam (Sistem Belleği):16 GB\nAğırlık:682 gr\nİşletim Sistemi:iPadOS 16\nBağlantı Özellikleri:Wi-Fi\nPil performansı:Belirtilmemiş',
    ),
    ProductModel(
      id: 18,
      image: Constants.tab2,
      name: 'Samsung Galaxy Tab S9',
      quantity: 0,
      price: 27999,
      rating: 4.6,
      reviews: '3.8 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Disk Kapasitesi:512 GB\nEkran Boyutu:14.6 inch\nÇözünürlük (Piksel):2960 x 1848\nRam (Sistem Belleği):12 GB\nAğırlık:732 gr.\nİşletim Sistemi:Android\nBağlantı Özellikleri:Wi-Fi Direct\nPil performansı:11200 mAh',
    ),
    ProductModel(
      id: 19,
      image: Constants.tv1,
      name: 'LG OLED97G29LA',
      quantity: 0,
      price: 588199,
      rating: 4.7,
      reviews: '1.9 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Boyutu:97 inch\nMonitör Tipi:LED\nMonitör Tipi:OLED\nÇözünürlük:4K Ultra HD\nEkran Boyu (cm):246\nHoparlör Gücü:60 W\nWi-Fi:Var\nÇözünürlük (Piksel):3840 x 2160',
    ),
    ProductModel(
      id: 20,
      image: Constants.tv2,
      name: 'SAMSUNG QE 98QN990CTXTK',
      quantity: 0,
      price: 569999,
      rating: 4.8,
      reviews: '3.8 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Boyutu:98 inch\nMonitör Tipi:QLED\nÇözünürlük:8K Ultra HD\nEkran Boyu (cm):245\nHoparlör Gücü:120 W\nWi-Fi:Var\nÇözünürlük (Piksel):7680 x 4320\nTarama Hızı:100 Hz',
    ),
    ProductModel(
      id: 21,
      image: Constants.dpc1,
      name: 'MSI GeForce RTX 4090',
      quantity: 0,
      price: 73635,
      rating: 4.9,
      reviews: '0.8 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Kartı Chipset Marka:NVIDIA®\nGrafik İşlemci:GeForce RTX 4090\nÇekirdek Hızı Maks.:2565 MHz\nÇekirdek Hücre Sayısı:16384 Cuda\nBellek Tipi:GDDR6X\nBellek Kapasitesi:24GB\nBellek Hızı:21000 MHz\nBellek Arayüzü:384 Bit',
    ),
    ProductModel(
      id: 22,
      image: Constants.dpc2,
      name: 'ASUS TUF GeForce RTX 4090',
      quantity: 0,
      price: 68433,
      rating: 4.8,
      reviews: '1.3 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Ekran Kartı Chipset Marka:NVIDIA®\nGrafik İşlemci:GeForce RTX 4090\nÇekirdek Hızı:2565 MHz\nÇekirdek Hızı Maks.:2595 MHz\nÇekirdek Hücre Sayısı:16384 Cuda\nBellek Tipi:GDDR6X\nBellek Kapasitesi:24GB\nBellek Hızı:21000 MHz',
    ),
    ProductModel(
      id: 23,
      image: Constants.prn1,
      name: 'BROTHER MFC-L9630CDN',
      quantity: 0,
      price: 103370,
      rating: 4.6,
      reviews: '0.8 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information:
          'Siyah Baskı Hızı:40 Sayfa/Dakika\nRenkli Baskı Hızı:Yok\nDubleks Baskı:Otomatik\nA3 Baskı:Yok\nWi-Fi:Yok\nFaks Özelliği:Yok\nGaranti:24\nMenşei:ÇİN',
    ),
    ProductModel(
      id: 24,
      image: Constants.prn2,
      name: 'HP DESIGN JET T650 36-in',
      quantity: 0,
      price: 90010,
      rating: 4.7,
      reviews: '1.3 bin satın alma',
      size: 'Siyah',
      isFavorite: false,
      information: 'Baskı Hızı:A1 kağıda 25 sn/sayfa, saatte 82 A1 baskısı\nModel Boyutu:914 mm\nMürekkep Türleri:Boya tabanlı (C, M, Y); pigment tabanlı (K)\nOrtam Kalınlığı (Metrik):0,3 mm''ye kadar\nKağıt Türleri:A4, A3, A2, A1, A0\nRulo Dış Çapı:100 mm\nOrtam Genişliği Max:914 mm\nYazdırılamayan Rulo Medya:5 x 5 x 5 x 5 mm',
    ),
  ];
}
